# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeoVenturesApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
   pod ‘Alamofire’
   pod ‘IQKeyboardManagerSwift’, ‘4.0.10'	
   pod ‘MBProgressHUD’
   pod 'ACFloatingTextfield-Swift', '~> 1.7'
   pod 'SDWebImage'
    pod 'SwiftyJSON'
  # Pods for GeoVenturesApp

end
